server:
  context-path: /dss
  port: 8087
logging:
  file: C:/java/MHC_LOGS/dss/dss.log
mhc:
  brms:
    guvnor:
      endpointAddress: http://BHITSDEVACS01/guvnor-5.5.0.Final-tomcat-6.0/rest/packages/AnnotationRules/source
      serviceUsername: admin
      servicePassword: admin
  dss:
    documentTagger:
      disclaimerText: disclaimerText