server:
  context-path: /dss
  port: 8450
  ssl:
    key-store: C:/ssl_keystore.keystore
    key-store-password: changeit
logging:
  file: C:/java/MHC_LOGS/dss/dss.log
mhc:
  brms:
    guvnor:
      endpointAddress: http://BHITSDEVACS01/guvnor-5.5.0.Final-tomcat-6.0/rest/packages/AnnotationRules/source
      serviceUsername: admin
      servicePassword: admin
  dss:
    redact:
      headersWhiteList:
        - "realmCode"
        - "typeId"
        - "templateId"
        - "id"
        - "code"
        - "title"
        - "effectiveTime"
        - "confidentialityCode"
        - "languageCode"
        - "setId"
        - "versionNumber"
        - "copyTime"
        - "recordTarget"
        - "author"
        - "dataEnterer"
        - "custodian"
        - "legalAuthenticator"
        - "inFulfillmentOf"
        - "documentationOf"
        - "relatedDocument"
        - "authorization"
        - "componentOf"
        - "component"
      sectionWhiteList:
        - "11450-4"
        - "48765-2"
        - "10160-0"
        - "30954-2"
    DocumentTaggerImpl:
      disclaimerText: |
                    &lt;disclaimerText&gt;
                    &lt;title&gt;***PLEASE READ THE
                    DISCLAIMER***&lt;/title&gt;
                    &lt;text&gt;The patient has authorized
                    the sharing of their continuity of care
                    document in a C32 summary
                    format that has been provided by Prince
                    George&amp;apos;s County
                    Health Department and its affiliates as a
                    partial
                    reference service;
                    it is not to be used as a substitute for a medical intake
                    process
                    and/or diagnosis, which must be provided by the
                    patient&amp;apos;s
                    own
                    physician or reviewing practitioner.
                    &lt;br/&gt;&lt;br/&gt;CAUTION:&lt;br/&gt;The following
                    history may
                    not be complete&lt;br/&gt;
                    &lt;list&gt;
                    &lt;item&gt;Patients may have
                    purchased or obtained care through sources which
                    bypass Prince
                    George&amp;apos;s County Health Department supplying the
                    history.&lt;/item&gt;
                    &lt;item&gt;Electronic Medical Record (EMR)
                    systems may have their own unique
                    method for accepting and/or
                    formatting data sent by the system of
                    origin.&lt;/item&gt;
                    &lt;/list&gt;
                    &lt;/text&gt;
                    &lt;/disclaimerText&gt;
    documentSegmentationImpl:
      defaultIsAudited: true
      defaultIsAuditFailureByPass: true
    ValueSetServiceImpl:
      endpointAddress: https://localhost:8446/pcm/lookupService