server:
  port: 8450
spring.profiles.active: eureka-ssl
logging:
  file: /java/MHC_LOGS/dss/dss.log
  level:
    gov.samhsa.mhc.dss: warn
info:
  component: DSS
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
# TODO: until finding a better solution, disable hystrix command timeout. See https://github.com/spring-cloud/spring-cloud-netflix/issues/321#issuecomment-97727313
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
mhc:
  brms:
    guvnor:
      endpointAddress: http://BHITSDEVHIE01/guvnor-5.5.0.Final-tomcat-6.0/rest/packages/AnnotationRules/source
      serviceUsername: admin
      servicePassword: admin
  dss:
    validator:
      c-cda:
        r1: https://localhost:8443/documentValidator/r1/validator
        r2: https://localhost:8443/documentValidator/r2/validator
    redact:
      headersWhiteList:
        - "realmCode"
        - "typeId"
        - "templateId"
        - "id"
        - "code"
        - "title"
        - "effectiveTime"
        - "confidentialityCode"
        - "languageCode"
        - "setId"
        - "versionNumber"
        - "copyTime"
        - "recordTarget"
        - "author"
        - "dataEnterer"
        - "custodian"
        - "legalAuthenticator"
        - "inFulfillmentOf"
        - "documentationOf"
        - "relatedDocument"
        - "authorization"
        - "componentOf"
        - "component"
      sectionWhiteList:
        - "11450-4" # problems
        - "48765-2" # allergies
        - "10160-0" # medications
        - "30954-2" # results
        - "29762-2" # social history
        - "8716-3" # vital signs
        - "47519-4" # procedures
    DocumentTaggerImpl:
      additionalSections:
        - code: PROHIBITION_ON_REDISCLOSURE
          codeSystem: 2.25.85119437033116720353817881047915448747
          codeSystemName: Consent2Share Disclaimer Codes
          displayName: PROHIBITION ON RE-DISCLOSURE
          title: "***PLEASE READ PROHIBITION ON RE-DISCLOSURE***"
          text: >
              "This information has been disclosed to you from records protected by
              Federal confidentiality rules (42 CFR part 2). The Federal rules prohibit
              you from making any further disclosure of this information unless further
              disclosure is expressly permitted by the written consent of the person to
              whom it pertains or as otherwise permitted by 42 CFR part 2. A general
              authorization for the release of medical or other information is NOT
              sufficient for this purpose. The Federal rules restrict any use of the
              information to criminally investigate or prosecute any alcohol or drug abuse
              patient."<br/>(42 C.F.R. ยง 2.32)
    documentSegmentationImpl:
      defaultIsAudited: true
      defaultIsAuditFailureByPass: true
    audit-service:
      host: BHITSDEVACS01
      port: 9630
---
spring.profiles: ssl
server:
  port: 8450
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /dss
---
spring.profiles: eureka-ssl
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
---
spring.profiles: pgchd
mhc:
  dss:
    DocumentTaggerImpl:
      additionalSections:
        - code: DISCLAIMER
          codeSystem: 2.25.85119437033116720353817881047915448747
          codeSystemName: Consent2Share Disclaimer Codes
          displayName: DISCLAIMER
          title: "***PLEASE READ THE DISCLAIMER***"
          text: >
              The patient has authorized the sharing of their continuity of care document in a C32 summary format that has been provided by Prince George's County Health Department and its affiliates as a partial reference service; it is not to be used as a substitute for a medical intake process and/or diagnosis, which must be provided by the patient's own physician or reviewing practitioner.<br/>
              <br/>CAUTION:<br/>The following history may not be complete<br/>
              <list>
                  <item>Patients may have purchased or obtained care through sources which bypass Prince George's County Health Department supplying the history.</item>
                  <item>Electronic Medical Record (EMR) systems may have their own unique method for accepting and/or formatting data sent by the system of origin.</item>
              </list>
        - code: PROHIBITION_ON_REDISCLOSURE
          codeSystem: 2.25.85119437033116720353817881047915448747
          codeSystemName: Consent2Share Disclaimer Codes
          displayName: PROHIBITION ON RE-DISCLOSURE
          title: "***PLEASE READ PROHIBITION ON RE-DISCLOSURE***"
          text: >
              "This information has been disclosed to you from records protected by
              Federal confidentiality rules (42 CFR part 2). The Federal rules prohibit
              you from making any further disclosure of this information unless further
              disclosure is expressly permitted by the written consent of the person to
              whom it pertains or as otherwise permitted by 42 CFR part 2. A general
              authorization for the release of medical or other information is NOT
              sufficient for this purpose. The Federal rules restrict any use of the
              information to criminally investigate or prosecute any alcohol or drug abuse
              patient."<br/>(42 C.F.R. ยง 2.32)
---
spring.profiles: docker
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.mhc.com:8761/eureka/
  instance:
    prefer-ip-address: true
mhc.dss:
  validator:
    c-cda:
      r1: https://document-validator-r1.mhc.com:8443/documentValidator/validator
      r2: https://document-validator.mhc.com:8443/documentValidator/validator
  audit-service:
    host: audit-service.mhc.com