server:
  port: 8450
logging:
  file: /java/C2S_LOGS/dss/dss.log
  level:
    gov.samhsa.c2s.dss: warn
info:
  component: DSS
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      # endpoint for discovery-server, pass '--eureka.client.protocol=https' if discovery-server is running on https
      defaultZone: ${eureka.client.protocol:http}://localhost:8761/eureka/

hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
c2s:
  brms:
    guvnor:
      endpointAddress: http://localhost:8080/guvnor/rest/packages/AnnotationRules/source
      serviceUsername: admin
      servicePassword: admin
  dss:
    validator:
      c-cda:
        r1: http://localhost:8080/documentValidator/r1/validator
        r2: http://localhost:8080/documentValidator/r2/validator
    redact:
      headersWhiteList:
        - "realmCode"
        - "typeId"
        - "templateId"
        - "id"
        - "code"
        - "title"
        - "effectiveTime"
        - "confidentialityCode"
        - "languageCode"
        - "setId"
        - "versionNumber"
        - "copyTime"
        - "recordTarget"
        - "author"
        - "dataEnterer"
        - "custodian"
        - "legalAuthenticator"
        - "inFulfillmentOf"
        - "documentationOf"
        - "relatedDocument"
        - "authorization"
        - "componentOf"
        - "component"
      sectionWhiteList:
        - "11450-4" # problems
        - "48765-2" # allergies
        - "10160-0" # medications
        - "30954-2" # results
        - "29762-2" # social history
        - "8716-3" # vital signs
        - "47519-4" # procedures
    DocumentTaggerImpl:
      additionalSections:
        - code: PROHIBITION_ON_REDISCLOSURE
          codeSystem: 2.25.85119437033116720353817881047915448747
          codeSystemName: Consent2Share Disclaimer Codes
          displayName: PROHIBITION ON RE-DISCLOSURE
          title: "***PLEASE READ PROHIBITION ON RE-DISCLOSURE***"
          text: >
              "This information has been disclosed to you from records protected by
              Federal confidentiality rules (42 CFR part 2). The Federal rules prohibit
              you from making any further disclosure of this information unless further
              disclosure is expressly permitted by the written consent of the person to
              whom it pertains or as otherwise permitted by 42 CFR part 2. A general
              authorization for the release of medical or other information is NOT
              sufficient for this purpose. The Federal rules restrict any use of the
              information to criminally investigate or prosecute any alcohol or drug abuse
              patient."<br/>(42 C.F.R. ยง 2.32)
    documentSegmentationImpl:
      defaultIsAudited: true
      defaultIsAuditFailureByPass: true
    audit-client:
      enabled: false
      host: localhost
      port: 9630
---
# Enables ssl in this service when activated
spring.profiles: ssl
server:
  port: 8450
  # Configure keystore and keystore password for ssl per environment
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
# Enables ssl and adds /phr context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /dss
---
spring.profiles: docker
eureka:
  client:
    service-url:
      defaultZone: ${eureka.client.protocol:http}://discovery-server.c2s.com:8761/eureka/
  instance:
    prefer-ip-address: true
c2s:
  dss:
    validator:
      c-cda:
        r1: http://document-validator-ccda-r1.c2s.com:8080/documentValidator/validator
        r2: http://document-validator-ccda-r2.c2s.com:8080/documentValidator/validator
    audit-service:
      host: logback-audit-server.c2s.com
  brms:
    guvnor:
      endpointAddress: http://guvnor.c2s.com:8080/guvnor/rest/packages/AnnotationRules/source